creation_rules:
  - path_regex: .*/\.env$
    age: "age1vtpq2s8s09w847xmypcaat3nqvkja72sthzxg4wtr4tplc3z5fysgsgpts"
  - path_regex: .*\.json$
    age: "age1vtpq2s8s09w847xmypcaat3nqvkja72sthzxg4wtr4tplc3z5fysgsgpts"
