http:
  routers:
    # Development Router
    dev-app:
      rule: "Host(`dev.bestfam.us`)"
      service: dev-app-service
      entryPoints:
        - web

    dev-app-secure:
      rule: "Host(`dev.bestfam.us`)"
      service: dev-app-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    dev-app-service:
      loadBalancer:
        servers:
          - url: "http://betting-dev-dashboard:3000"
