http:
  routers:
    # Development Routers (Still on Host for now if desired)
    dev-app-secure:
      rule: "Host(`dev.bestfam.us`)"
      service: dev-app-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    dev-app:
      rule: "Host(`dev.bestfam.us`)"
      service: dev-app-service
      entryPoints:
        - web

  services:
    dev-app-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
